## Key bindings

# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 0
set-option -g focus-events on

# Reload settings
bind r source-file ~/.config/tmux/tmux.conf

# Open window/session switcher
bind-key o run-shell -b "/Users/rafael/.config/tmux/plugins/tmux-fzf/scripts/session.sh attach"
bind-key p run-shell -b "/Users/rafael/.config/tmux/plugins/tmux-fzf/scripts/window.sh switch"

# Split panes (I'm mirroring my bindings for Neovim but with Tmux leader)
bind -r - split-window -v
bind -r | split-window -h

# Smart pane switching with awareness of vim splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key L resize-pane -R 10
bind-key H resize-pane -L 10

# Maximize pane
bind -r m resize-pane -Z

# Moving window
bind-key -n C-S-h swap-window -t -1 \; previous-window
bind-key -n C-S-l swap-window -t +1 \; next-window

# Switching windows
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 0

# Toggle synchronization of keystrokes to all panes in the window
bind * set-window-option synchronize-panes

# basic settings
set -g detach-on-destroy off # don't exit from tmux when closing a session
set-option -g status-justify "left"

# allows buffer scrollback in a tmux session.
set -g mouse on
set-option -g history-limit 200000 # Increase scrollback buffer size
set -sg escape-time 0
set-option -s set-clipboard on # Enable system clipboard integration
set -g status-position top

## COLOR
# True color settings
set-option -g default-terminal "screen-256color"
set -sa terminal-overrides ",$xterm*:Tc" # Enable true color support for xterm-compatible terminals
set-option -g allow-passthrough on

# window
set -g base-index 1 # start indexing windows at 1 instead of 0
set -g pane-base-index 1
set -g renumber-windows on # renumber all windows when a window is closed
set-window-option -g mode-keys vi # Set vi key bindings for copy mode

# # Title Bar
# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Configure Tmux Plugin Manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Statusline configs
source ~/.config/tmux/statusline.conf

# Plugins configs
set -g @tpm-clean 'X'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

TMUX_FZF_LAUNCH_KEY="f"
TMUX_FZF_PREVIEW=0
TMUX_FZF_PREVIEW_FOLLOW=0

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
